name: Automationexercise Cypress Test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cypress Test - Chrome
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run
          browser: chrome
      - uses: actions/upload-artifact@v3
        with:
          name: Automationexercise Test Report - Chrome
          path: cypress/reports